---
- hosts: localhost
  become: yes

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
      - wget
      - curl
      - vim
      - apt-transport-https
      - ca-certificates
      - aptitude
      - pv
      - xclip
      - less
      - htop
      - pandoc
      - lynx

    - name: add readme function
      lineinfile:
        path: /etc/profile.d/parsereadme.sh
        line: 'readme () { pandoc $1 | lynx -stdin }'
        create: yes
        state: present
        owner: root
        group: root
        mode: 'u=rw,go=r'
