---
- hosts: localhost
  become: yes

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
      - wget
      - curl
      - vim
      - apt-transport-https
      - ca-certificates
      - aptitude
      - pv
      - xclip
      - less
      - htop