---
- hosts: all
  become: yes
  roles:
    - qtdevel

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
      - make
      - automake
      - autoconf
      - libtool
      - libtool-bin
      - g++
      - valgrind
      - bison
      - byacc
      - flex
      - libprotobuf-c-dev
      - libprotobuf-c1
      - libprotobuf-c1-dbg
      - protobuf-c-compiler
      - libunwind-dev

    # add qtcreator to path
    - name: make sure /etc/profile.d exists
      become: yes
      file:
        path: /etc/profile.d
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'

    - name: add qtcreator to path
      lineinfile:
        path: /etc/profile.d/qtcreator.sh
        line: 'export PATH=$PATH:/opt/Qt/Tools/QtCreator/bin/'
        create: yes
        state: present
        owner: root
        group: root
        mode: 'u=rw,go=r'
