---
- hosts: all
  become: yes
  vars_files:
    - vars/vagrant.yml
  roles:
    - pixelart.vagrant
    - andrewrothstein.packer
    - angstwad.docker_ubuntu
    - geerlingguy.git

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
      - libffi-dev
      - libssl-dev
      - build-essential
      - liblzma-dev
      - protobuf-compiler
      - tig
      - rpm

    - name: Install rocker
      shell: curl -SL https://github.com/grammarly/rocker/releases/download/1.3.0/rocker_linux_amd64.tar.gz | tar -xzC /usr/local/bin && chmod +x /usr/local/bin/rocker
      args:
        creates: /usr/local/bin/rocker