---
- hosts: localhost
  become: yes

  tasks:
    - apt: "name={{ item }} state=installed"
      with_items:
      - hardinfo
      - indicator-multiload
      - compizconfig-settings-manager
      - compiz-plugins