---
- hosts: localhost
  become: yes

  tasks:
    - apt:
        name: "{{ item }}"
      with_items:
      - hardinfo
      - indicator-multiload
      - compizconfig-settings-manager
      - compiz-plugins
      - update-manager-core
